name: VenturaCalendar
version: '${version}'
main: me.m0dii.venturacalendar.VenturaCalendar
api-version: '1.21'  
authors: [M0dii]
description: Calendar plugin for Minecraft servers
softdepend: [PlaceholderAPI]
commands:
  venturacalendar:
    description: Base command
    permission: venturacalendar.command.vc
    usage: /<command>
    aliases: [venturacal, vc]
  calendar:
    description: Calendar command
    permission: venturacalendar.command.calendar
    usage: /<command>
    aliases: [cal]
permissions:
  venturacalendar.command.venturacalendar:
    description: Permission to use base command.
    default: op
  venturacalendar.command.changetime:
    description: Permission to add/subtract time, set starting year.
  venturacalendar.command.reload:
    description: Permission to reload the plugin.
    default: op
  venturacalendar.command.calendar:
    description: Permission to use the calendar command.